version: "3.9"

services:
  backend:
    image: vxllx/recmind-backend:latest
    container_name: recmind-backend
    env_file:
      - .env
    ports:
      - "8000:8000"

    # âœ… Persist ONLY data
    volumes:
      - recmind_data:/app/backend/data

    restart: unless-stopped

volumes:
  recmind_data:
